-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Gazdă: localhost:3306
-- Timp de generare: apr. 07, 2026 la 03:23 PM
-- Versiune server: 10.11.16-MariaDB-cll-lve
-- Versiune PHP: 8.4.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Bază de date: `magazi15_ShergeiCovoare`
--

-- --------------------------------------------------------

--
-- Structură tabel pentru tabel `products`
--

CREATE TABLE `products` (
  `sort_ordine` int(11) NOT NULL DEFAULT 0,
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` decimal(10,0) NOT NULL DEFAULT 0,
  `lungime_cm` decimal(7,2) DEFAULT NULL,
  `latime_cm` decimal(7,2) DEFAULT NULL,
  `img` varchar(255) DEFAULT NULL,
  `description` mediumtext DEFAULT NULL,
  `preview` varchar(255) DEFAULT NULL,
  `stock` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `active` tinyint(1) DEFAULT 1,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `diameter_cm` decimal(7,2) NOT NULL DEFAULT 100.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Eliminarea datelor din tabel `products`
--

INSERT INTO `products` (`sort_ordine`, `id`, `name`, `price`, `lungime_cm`, `latime_cm`, `img`, `description`, `preview`, `stock`, `created_at`, `active`, `updated_at`, `deleted_at`, `diameter_cm`) VALUES
(20, 31, 'Mocheta Dreptunghiulara 2', 525, 160.00, 100.00, 'Image1.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(40, 32, 'Mocheta Dreptunghiulara 4', 525, 160.00, 100.00, 'Image2.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(30, 33, 'Mocheta Dreptunghiulara 3', 525, 160.00, 100.00, 'Image3.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(50, 34, 'Mocheta Dreptunghiulara 5', 525, 160.00, 100.00, 'Image4.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(60, 35, 'Mocheta Dreptunghiulara 6', 525, 160.00, 100.00, 'Image5.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(70, 36, 'Mocheta Dreptunghiulara 7', 525, 160.00, 100.00, 'Image6.png', 'Un covor PsyGeometry autentic lucrat manual cu motive traditionale elaborate.O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(80, 37, 'Mocheta Dreptunghiulara 8', 525, 160.00, 100.00, 'Image7.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(90, 38, 'Mocheta Dreptunghiulara 9', 525, 160.00, 100.00, 'Image8.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(100, 39, 'Mocheta Dreptunghiulara 10', 525, 160.00, 100.00, 'Image9.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(110, 40, 'Mocheta Dreptunghiulara 11', 525, 160.00, 100.00, 'Image10.png', 'Un covor PsyGeometry autentic lucrat manual cu motive traditionale elaborate.O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(120, 41, 'Mocheta Dreptunghiulara 12', 525, 160.00, 100.00, 'Image11.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(130, 42, 'Mocheta Dreptunghiulara 13', 525, 160.00, 100.00, 'Image12.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(140, 43, 'Mocheta Dreptunghiulara 14', 525, 160.00, 100.00, 'Image13.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(150, 44, 'Mocheta Dreptunghiulara 15', 525, 160.00, 100.00, 'Image14.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(160, 45, 'Mocheta Dreptunghiulara 16', 525, 160.00, 100.00, 'Image15.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(170, 46, 'Mocheta Dreptunghiulara 17', 525, 160.00, 100.00, 'Image16.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(180, 47, 'Mocheta Dreptunghiulara 18', 525, 160.00, 100.00, 'Image17.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(190, 48, 'Mocheta Dreptunghiulara 19', 525, 160.00, 100.00, 'Image18.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(200, 49, 'Mocheta Dreptunghiulara 20', 525, 160.00, 100.00, 'Image19.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(210, 50, 'Mocheta Dreptunghiulara 21', 525, 160.00, 100.00, 'Image20.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(220, 51, 'Mocheta Dreptunghiulara 22', 525, 160.00, 100.00, 'Image21.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(230, 52, 'Mocheta Dreptunghiulara 23', 525, 160.00, 100.00, 'Image22.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(240, 53, 'Mocheta Dreptunghiulara 24', 525, 160.00, 100.00, 'Image23.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(250, 54, 'Mocheta Dreptunghiulara 25', 525, 160.00, 100.00, 'Image24.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(260, 55, 'Mocheta Dreptunghiulara 26', 525, 160.00, 100.00, 'Image25.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(270, 56, 'Mocheta Dreptunghiulara 27', 525, 160.00, 100.00, 'Image26.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(280, 57, 'Mocheta Dreptunghiulara 28', 525, 160.00, 100.00, 'Image27.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(290, 58, 'Mocheta Dreptunghiulara 29', 525, 160.00, 100.00, 'Image28.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(300, 59, 'Mocheta Dreptunghiulara 30', 525, 160.00, 100.00, 'Image29.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(310, 60, 'Mocheta Dreptunghiulara 31', 525, 160.00, 100.00, 'Image30.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(320, 61, 'Mocheta Dreptunghiulara 32', 525, 160.00, 100.00, 'Image31.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(330, 62, 'Mocheta Dreptunghiulara 33', 525, 160.00, 100.00, 'Image32.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(340, 63, 'Mocheta Dreptunghiulara 34', 525, 160.00, 100.00, 'Image33.jpg', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(350, 64, 'Mocheta Dreptunghiulara 35', 525, 160.00, 100.00, 'Image34.jpg', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(360, 65, 'Mocheta Dreptunghiulara 36', 525, 160.00, 100.00, 'Image35.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(370, 66, 'Mocheta Dreptunghiulara 37', 525, 160.00, 100.00, 'Image36.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(380, 67, 'Mocheta Dreptunghiulara 38', 525, 160.00, 100.00, 'Image37.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(390, 68, 'Mocheta Dreptunghiulara 39', 525, 160.00, 100.00, 'Image38.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(400, 69, 'Mocheta Dreptunghiulara 40', 525, 160.00, 100.00, 'Image39.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(10, 70, 'Mocheta Dreptunghiulara 1', 525, 160.00, 100.00, 'Image40.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(410, 71, 'Mocheta Dreptunghiulara 41', 525, 160.00, 100.00, 'Image41.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(420, 72, 'Mocheta Dreptunghiulara 42', 525, 160.00, 100.00, 'Image42.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(430, 73, 'Mocheta Dreptunghiulara 43', 525, 160.00, 100.00, 'Image43.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(440, 74, 'Mocheta Dreptunghiulara 44', 525, 160.00, 100.00, 'Image44.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(450, 75, 'Mocheta Dreptunghiulara 45', 525, 160.00, 100.00, 'Image45.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(460, 76, 'Mocheta Dreptunghiulara 46', 525, 160.00, 100.00, 'Image46.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(470, 77, 'Mocheta Dreptunghiulara 47', 525, 160.00, 100.00, 'Image47.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(480, 78, 'Mocheta Dreptunghiulara 48', 525, 160.00, 100.00, 'Image48.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(490, 79, 'Mocheta Dreptunghiulara 49', 525, 160.00, 100.00, 'Image49.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(500, 80, 'Mocheta Dreptunghiulara 50', 525, 160.00, 100.00, 'Image50.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(510, 81, 'Mocheta Dreptunghiulara 51', 525, 160.00, 100.00, 'Image51.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(520, 82, 'Mocheta Dreptunghiulara 52', 525, 160.00, 100.00, 'Image52.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(530, 83, 'Mocheta Dreptunghiulara 53', 525, 160.00, 100.00, 'Image53.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(540, 84, 'Mocheta Dreptunghiulara 54', 525, 160.00, 100.00, 'Image54.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(550, 85, 'Mocheta Dreptunghiulara 55', 525, 160.00, 100.00, 'Image55.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(560, 86, 'Mocheta Dreptunghiulara 56', 525, 160.00, 100.00, 'Image56.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(570, 87, 'Mocheta Dreptunghiulara 57', 525, 160.00, 100.00, 'Image57.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(580, 88, 'Mocheta Dreptunghiulara 58', 525, 160.00, 100.00, 'Image58.jpg', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(590, 89, 'Mocheta Dreptunghiulara 59', 525, 160.00, 100.00, 'Image59.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(600, 90, 'Mocheta Dreptunghiulara 60', 525, 160.00, 100.00, 'Image60.png', 'O mocheta autentica PsyGeometry printata\n\n\nEste o poartă vizuală către armonia interioară, unde simbolurile sacre și geometria divină se împletesc într-un câmp energetic de echilibru și conștiință. Centrul său radiant evocă unitatea dintre minte, spirit și univers, invitând privitorul la introspecție, claritate și reconectare cu esența profundă a ființei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00),
(0, 91, 'Ingeras 1', 10, 5.00, 2.00, 'Image61.png', 'Legenda Îngerilor Păcii\n\n\nSe spune că, în anul 1887, în liniștea adâncă a Sfântului Munte Athos, la Schitul românesc Prodromu, călugării se adunau în nopțile de priveghere pentru a se ruga Maicii Domnului pentru pacea lumii.\n\nÎn acea perioadă tulbure, oamenii erau despărțiți de ură, de războaie și de neînțelegeri. Iar monahii știau că singura putere care poate vindeca lumea este rugăciunea născută din iubire.\n\nÎntr-una dintre acele nopți, ei au rostit cu credință o rugăciune către Maica Domnului – Maica Păcii, cerând ca pacea să coboare peste omenire.\n\nRugăciunea Maicii Păcii\n\n\n„Doamnă prea milostivă, Regină a cerurilor, Maică a Păcii și dătătoare de iubire,\nla Tine ne îndreptăm cu tristețe și speranță.\nÎmpacă-i pe cei care se luptă, luminează-i pe cei care urăsc, stinge flăcările discordiei.\nRoagă-Te Fiului Tău, Domnului nostru Iisus Hristos, ca pacea să domnească în întreaga lume,\nca oamenii să trăiască în unitate și bucurie, slăvind numele Lui.\nFii mijlocitoarea și păzitoarea noastră în toate zilele vieții noastre.\n\nAmin.”\n\nMonahii spuneau că atunci când această rugăciune era rostită cu inimă curată, cerul răspundea.\n\nȘi că fiecare rugăciune pentru pace trimite în lume un înger al păcii.\n\nAcești îngeri nu sunt văzuți cu ochii trupului.\nDar ei sunt simțiți în sufletul oamenilor atunci când apare:\nliniștea,\nîmpăcarea,\nsperanța.\n\nAstfel s-a născut Legenda Îngerilor Păcii.', NULL, 10, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 92, 'Ingeras 2', 10, 5.00, 2.00, 'Image62.png', 'Legenda Îngerilor Păcii\n\n\nSe spune că, în anul 1887, în liniștea adâncă a Sfântului Munte Athos, la Schitul românesc Prodromu, călugării se adunau în nopțile de priveghere pentru a se ruga Maicii Domnului pentru pacea lumii.\n\nÎn acea perioadă tulbure, oamenii erau despărțiți de ură, de războaie și de neînțelegeri. Iar monahii știau că singura putere care poate vindeca lumea este rugăciunea născută din iubire.\n\nÎntr-una dintre acele nopți, ei au rostit cu credință o rugăciune către Maica Domnului – Maica Păcii, cerând ca pacea să coboare peste omenire.\n\nRugăciunea Maicii Păcii\n\n\n„Doamnă prea milostivă, Regină a cerurilor, Maică a Păcii și dătătoare de iubire,\nla Tine ne îndreptăm cu tristețe și speranță.\nÎmpacă-i pe cei care se luptă, luminează-i pe cei care urăsc, stinge flăcările discordiei.\nRoagă-Te Fiului Tău, Domnului nostru Iisus Hristos, ca pacea să domnească în întreaga lume,\nca oamenii să trăiască în unitate și bucurie, slăvind numele Lui.\nFii mijlocitoarea și păzitoarea noastră în toate zilele vieții noastre.\n\nAmin.”\n\nMonahii spuneau că atunci când această rugăciune era rostită cu inimă curată, cerul răspundea.\n\nȘi că fiecare rugăciune pentru pace trimite în lume un înger al păcii.\n\nAcești îngeri nu sunt văzuți cu ochii trupului.\nDar ei sunt simțiți în sufletul oamenilor atunci când apare:\nliniștea,\nîmpăcarea,\nsperanța.\n\nAstfel s-a născut Legenda Îngerilor Păcii.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 93, 'Ingeras 3', 10, 5.00, 2.00, 'Image63.png', 'Legenda Îngerilor Păcii\n\n\nSe spune că, în anul 1887, în liniștea adâncă a Sfântului Munte Athos, la Schitul românesc Prodromu, călugării se adunau în nopțile de priveghere pentru a se ruga Maicii Domnului pentru pacea lumii.\n\nÎn acea perioadă tulbure, oamenii erau despărțiți de ură, de războaie și de neînțelegeri. Iar monahii știau că singura putere care poate vindeca lumea este rugăciunea născută din iubire.\n\nÎntr-una dintre acele nopți, ei au rostit cu credință o rugăciune către Maica Domnului – Maica Păcii, cerând ca pacea să coboare peste omenire.\n\nRugăciunea Maicii Păcii\n\n\n„Doamnă prea milostivă, Regină a cerurilor, Maică a Păcii și dătătoare de iubire,\nla Tine ne îndreptăm cu tristețe și speranță.\nÎmpacă-i pe cei care se luptă, luminează-i pe cei care urăsc, stinge flăcările discordiei.\nRoagă-Te Fiului Tău, Domnului nostru Iisus Hristos, ca pacea să domnească în întreaga lume,\nca oamenii să trăiască în unitate și bucurie, slăvind numele Lui.\nFii mijlocitoarea și păzitoarea noastră în toate zilele vieții noastre.\n\nAmin.”\n\nMonahii spuneau că atunci când această rugăciune era rostită cu inimă curată, cerul răspundea.\n\nȘi că fiecare rugăciune pentru pace trimite în lume un înger al păcii.\n\nAcești îngeri nu sunt văzuți cu ochii trupului.\nDar ei sunt simțiți în sufletul oamenilor atunci când apare:\nliniștea,\nîmpăcarea,\nsperanța.\n\nAstfel s-a născut Legenda Îngerilor Păcii.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 94, 'Ingeras 4', 10, 5.00, 2.00, 'Image64.png', 'Legenda Îngerilor Păcii\n\n\nSe spune că, în anul 1887, în liniștea adâncă a Sfântului Munte Athos, la Schitul românesc Prodromu, călugării se adunau în nopțile de priveghere pentru a se ruga Maicii Domnului pentru pacea lumii.\n\nÎn acea perioadă tulbure, oamenii erau despărțiți de ură, de războaie și de neînțelegeri. Iar monahii știau că singura putere care poate vindeca lumea este rugăciunea născută din iubire.\n\nÎntr-una dintre acele nopți, ei au rostit cu credință o rugăciune către Maica Domnului – Maica Păcii, cerând ca pacea să coboare peste omenire.\n\nRugăciunea Maicii Păcii\n\n\n„Doamnă prea milostivă, Regină a cerurilor, Maică a Păcii și dătătoare de iubire,\nla Tine ne îndreptăm cu tristețe și speranță.\nÎmpacă-i pe cei care se luptă, luminează-i pe cei care urăsc, stinge flăcările discordiei.\nRoagă-Te Fiului Tău, Domnului nostru Iisus Hristos, ca pacea să domnească în întreaga lume,\nca oamenii să trăiască în unitate și bucurie, slăvind numele Lui.\nFii mijlocitoarea și păzitoarea noastră în toate zilele vieții noastre.\n\nAmin.”\n\nMonahii spuneau că atunci când această rugăciune era rostită cu inimă curată, cerul răspundea.\n\nȘi că fiecare rugăciune pentru pace trimite în lume un înger al păcii.\n\nAcești îngeri nu sunt văzuți cu ochii trupului.\nDar ei sunt simțiți în sufletul oamenilor atunci când apare:\nliniștea,\nîmpăcarea,\nsperanța.\n\nAstfel s-a născut Legenda Îngerilor Păcii.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 95, 'Ingeras 5', 10, 5.00, 2.00, 'Image65.png', 'Legenda Îngerilor Păcii\n\n\nSe spune că, în anul 1887, în liniștea adâncă a Sfântului Munte Athos, la Schitul românesc Prodromu, călugării se adunau în nopțile de priveghere pentru a se ruga Maicii Domnului pentru pacea lumii.\n\nÎn acea perioadă tulbure, oamenii erau despărțiți de ură, de războaie și de neînțelegeri. Iar monahii știau că singura putere care poate vindeca lumea este rugăciunea născută din iubire.\n\nÎntr-una dintre acele nopți, ei au rostit cu credință o rugăciune către Maica Domnului – Maica Păcii, cerând ca pacea să coboare peste omenire.\n\nRugăciunea Maicii Păcii\n\n\n„Doamnă prea milostivă, Regină a cerurilor, Maică a Păcii și dătătoare de iubire,\nla Tine ne îndreptăm cu tristețe și speranță.\nÎmpacă-i pe cei care se luptă, luminează-i pe cei care urăsc, stinge flăcările discordiei.\nRoagă-Te Fiului Tău, Domnului nostru Iisus Hristos, ca pacea să domnească în întreaga lume,\nca oamenii să trăiască în unitate și bucurie, slăvind numele Lui.\nFii mijlocitoarea și păzitoarea noastră în toate zilele vieții noastre.\n\nAmin.”\n\nMonahii spuneau că atunci când această rugăciune era rostită cu inimă curată, cerul răspundea.\n\nȘi că fiecare rugăciune pentru pace trimite în lume un înger al păcii.\n\nAcești îngeri nu sunt văzuți cu ochii trupului.\nDar ei sunt simțiți în sufletul oamenilor atunci când apare:\nliniștea,\nîmpăcarea,\nsperanța.\n\nAstfel s-a născut Legenda Îngerilor Păcii.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 100, 'Mandala 1', 5, 2.00, 2.00, 'Image71.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 10, '2026-02-23 11:54:20', 1, NULL, NULL, 0.00),
(0, 101, 'Mandala 2', 5, 2.00, 2.00, 'Image72.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 11:54:20', 1, NULL, NULL, 0.00),
(0, 102, 'Mandala 3', 5, 2.00, 2.00, 'Image73.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 103, 'Mandala 4', 5, 2.00, 2.00, 'Image74.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 104, 'Mandala 5', 5, 2.00, 2.00, 'Image75.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00);
INSERT INTO `products` (`sort_ordine`, `id`, `name`, `price`, `lungime_cm`, `latime_cm`, `img`, `description`, `preview`, `stock`, `created_at`, `active`, `updated_at`, `deleted_at`, `diameter_cm`) VALUES
(0, 105, 'Mandala 6', 5, 2.00, 2.00, 'Image76.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 106, 'Mandala 7', 5, 2.00, 2.00, 'Image77.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 107, 'Mandala 8', 5, 2.00, 2.00, 'Image78.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 108, 'Mandala 9', 5, 2.00, 2.00, 'Image79.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 109, 'Mandala 10', 5, 2.00, 2.00, 'Image80.png', 'Această mandală este neobișnuită.\nAre propriul ei secret.\nLotusul cu unsprezece petale simbolizează renașterea, din cenușa focului Creatorului într-o floare frumoasă cu unsprezece petale. Ajută foarte mult la renașterea dintr-o formă rea într-una bună; dintr-o situație imposibilă, există o cale de ieșire spre siguranță și o soluție frumoasă.\nSub acest lotus, această mandală, se află o mandală cu opt lotusuri. Reprezintă cele opt puteri divine. Acestea se numesc siddhi. Ceea ce este imposibil devine posibil. Aceasta este puterea lotusului cu opt petale.\nDar ele sunt unite de lotusul cu trei petale, această mandală. Această mandală reprezintă Sfânta Treime.\nFrumoasa combinație a acestor trei mandale permite abordarea misterelor lumii.\n3 plus 8 plus 11 formează o mandală cu douăzeci de lotusuri. Nimeni nu a mai făcut asta până acum. Acesta este secretul meu.\nDar ce este 22? Aceasta este muzica cerească a sferelor cu toate notele cosmice. În muzică, avem 5 clape negre și 7 clape albe la pian. Dar orga are sunete care fie cresc, fie scad sunetul, vibrația. Orga mare de biserică a lui Johann Sebastian Bach are 22 de note. Cu o astfel de orgă cu 22 de note, compozitorul putea schimba vibrațiile din corpul uman, ceea ce s-a întâmplat și la concertul său de la Viena, Austria. Acest lucru l-a speriat foarte tare pe regele Austriei, și pe supușii săi, înțelegând că acest lucru ar putea schimba puterea organelor din corpul uman și l-ar putea manipula. Dar aceasta este muzică, nu o mandală. Mandala cu 22 de petale rezonează în noi atunci când privim această floare de lotus - o mandală. Acestea au rămas în notația muzicală până în ziua de azi. Se numesc note întregi, dar există un sunet fundamental, vibrația, ascuțit, bemol și natural. Un total de 22 de sunete de vibrație. Un ajutor în viața noastră este o astfel de mandală în casa ta. Un covor, un medalion cu magnet sau o pictură murală. Cumpără unul și descoperă-te pe tine însuți și puterea lotusului cu 22 de petale și a mandalei.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 111, 'Tablou 1', 50, 42.00, 30.00, 'Image81.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 11:54:20', 1, NULL, NULL, 0.00),
(0, 112, 'Tablou 2', 50, 42.00, 30.00, 'Image82.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 11:54:20', 1, NULL, NULL, 0.00),
(0, 113, 'Tablou 3', 50, 42.00, 30.00, 'Image83.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 114, 'Tablou 4', 50, 42.00, 30.00, 'Image84.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 115, 'Tablou 5', 50, 42.00, 30.00, 'Image85.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 116, 'Tablou 6', 50, 42.00, 30.00, 'Image86.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 117, 'Tablou 7', 50, 42.00, 30.00, 'Image87.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 118, 'Tablou 8', 50, 42.00, 30.00, 'Image88.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 119, 'Tablou 9', 50, 42.00, 30.00, 'Image89.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 120, 'Tablou 10', 50, 42.00, 30.00, 'Image90.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 121, 'Tablou 11', 50, 42.00, 30.00, 'Image91.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 122, 'Tablou 12', 50, 42.00, 30.00, 'Image92.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 123, 'Tablou 13', 50, 42.00, 30.00, 'Image93.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 124, 'Tablou 14', 50, 42.00, 30.00, 'Image94.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 125, 'Tablou 15', 50, 42.00, 30.00, 'Image95.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 126, 'Tablou 16', 50, 42.00, 30.00, 'Image96.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 127, 'Tablou 17', 50, 42.00, 30.00, 'Image97.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 128, 'Tablou 18', 50, 42.00, 30.00, 'Image98.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 129, 'Tablou 19', 50, 42.00, 30.00, 'Image99.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 130, 'Tablou 20', 50, 42.00, 30.00, 'Image100.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 131, 'Tablou 21', 50, 42.00, 30.00, 'Image101.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 132, 'Tablou 22', 50, 42.00, 30.00, 'Image102.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 133, 'Tablou 23', 50, 42.00, 30.00, 'Image103.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 134, 'Tablou 24', 50, 42.00, 30.00, 'Image104.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 135, 'Tablou 25', 50, 42.00, 30.00, 'Image105.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 136, 'Tablou 26', 50, 42.00, 30.00, 'Image106.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 137, 'Tablou 27', 50, 42.00, 30.00, 'Image107.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 138, 'Tablou 28', 50, 42.00, 30.00, 'Image108.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 139, 'Tablou 29', 50, 42.00, 30.00, 'Image109.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 140, 'Tablou 30', 50, 42.00, 30.00, 'Image110.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 141, 'Tablou 31', 50, 42.00, 30.00, 'Image111.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 142, 'Tablou 32', 50, 42.00, 30.00, 'Image112.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 143, 'Tablou 33', 50, 42.00, 30.00, 'Image113.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 144, 'Tablou 34', 50, 42.00, 30.00, 'Image114.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 145, 'Tablou 35', 50, 42.00, 30.00, 'Image115.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 146, 'Tablou 36', 50, 42.00, 30.00, 'Image116.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 147, 'Tablou 37', 50, 42.00, 30.00, 'Image117.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 148, 'Tablou 38', 50, 42.00, 30.00, 'Image118.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 149, 'Tablou 39', 50, 42.00, 30.00, 'Image119.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 150, 'Tablou 40', 50, 42.00, 30.00, 'Image120.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 151, 'Tablou 41', 50, 42.00, 30.00, 'Image121.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 152, 'Tablou 42', 50, 42.00, 30.00, 'Image122.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 153, 'Tablou 43', 50, 42.00, 30.00, 'Image123.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 154, 'Tablou 44', 50, 42.00, 30.00, 'Image124.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00),
(0, 155, 'Tablou 45', 50, 42.00, 30.00, 'Image125.png\r\n', 'Arhanghel Metatron și sigila-glif Moșek, sunt concepute pentru a ne oferi ajutor in viata. Energia acestui tablou Artefact schimba in bine campul energetic in casa, la birou si oriunde este asezat.', 'Arhanghel Metatron ajuta in tot ce facem', 0, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00),
(0, 156, 'Tablou 46', 50, 42.00, 30.00, 'Image126.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00),
(0, 161, 'Mocheta Rotunda PsyGeometry 1', 350, NULL, NULL, 'Image131.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 162, 'Mocheta Rotunda PsyGeometry 2', 350, NULL, NULL, 'Image132.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 163, 'Mocheta Rotunda PsyGeometry 3', 350, NULL, NULL, 'Image133.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 164, 'Mocheta Rotunda PsyGeometry 4', 350, NULL, NULL, 'Image134.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 165, 'Mocheta Rotunda PsyGeometry 5', 350, NULL, NULL, 'Image135.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 166, 'Mocheta Rotunda PsyGeometry 6', 350, NULL, NULL, 'Image136.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 167, 'Mocheta Rotunda PsyGeometry 7', 350, NULL, NULL, 'Image137.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 168, 'Mocheta Rotunda PsyGeometry 8', 350, NULL, NULL, 'Image138.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 169, 'Mocheta Rotunda PsyGeometry 9', 350, NULL, NULL, 'Image139.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 170, 'Mocheta Rotunda PsyGeometry 10', 350, NULL, NULL, 'Image140.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 171, 'Mocheta Rotunda PsyGeometry 11', 350, NULL, NULL, 'Image141.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 172, 'Mocheta Rotunda PsyGeometry 12', 350, NULL, NULL, 'Image142.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 173, 'Mocheta Rotunda PsyGeometry 13', 350, NULL, NULL, 'Image143.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00),
(0, 174, 'Mocheta Rotunda PsyGeometry 14', 350, NULL, NULL, 'Image144.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00),
(0, 175, 'Mocheta Rotunda PsyGeometry 15', 350, NULL, NULL, 'Image145.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00),
(0, 176, 'Mocheta Rotunda PsyGeometry 16', 350, NULL, NULL, 'Image146.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00),
(0, 177, 'Mocheta Rotunda PsyGeometry 17', 350, NULL, NULL, 'Image147.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00),
(0, 178, 'Mocheta Rotunda PsyGeometry 18', 350, NULL, NULL, 'Image148.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', '', 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00);

--
-- Indexuri pentru tabele eliminate
--

--
-- Indexuri pentru tabele `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pentru tabele eliminate
--

--
-- AUTO_INCREMENT pentru tabele `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=180;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
