-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Gazdă: localhost:3306
-- Timp de generare: iun. 05, 2026 la 04:26 PM
-- Versiune server: 10.11.16-MariaDB-cll-lve
-- Versiune PHP: 8.4.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Bază de date: `magazi15_ShergeiCovoare`
--

-- --------------------------------------------------------

--
-- Structură tabel pentru tabel `products`
--

CREATE TABLE `products` (
  `sort_ordine` int(11) NOT NULL DEFAULT 0,
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` decimal(10,0) NOT NULL DEFAULT 0,
  `lungime_cm` decimal(7,2) DEFAULT NULL,
  `latime_cm` decimal(7,2) DEFAULT NULL,
  `img` varchar(255) DEFAULT NULL,
  `description` mediumtext DEFAULT NULL,
  `preview` varchar(255) DEFAULT NULL,
  `stock` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `active` tinyint(1) DEFAULT 1,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `diameter_cm` decimal(7,2) NOT NULL DEFAULT 100.00,
  `material` varchar(255) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Eliminarea datelor din tabel `products`
--

INSERT INTO `products` (`sort_ordine`, `id`, `name`, `price`, `lungime_cm`, `latime_cm`, `img`, `description`, `preview`, `stock`, `created_at`, `active`, `updated_at`, `deleted_at`, `diameter_cm`, `material`, `category`) VALUES
(2, 31, 'Mocheta Dreptunghiulara 2', 0, 160.00, 100.00, 'Image1.png', 'Glifele - semnături ale puterilor angelice, sigilii din cărți secrete despre puterile ființelor angelice și celeste, mandale ale rugăciunilor și mantrelor, conferă acestui covor modelele sale unice. Acest covor-artefact este ca un talisman pentru noroc, fericire și sănătate în destinul oricui îndrăznește să-l ia în casa, apartamentul sau biroul său.', '', 1, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, '', 'PsyGeometry'),
(5, 32, 'Mocheta Dreptunghiulara 5', 0, 160.00, 100.00, 'Image2.png', 'O lucrare personală a autorului, Sergey Danshin. Un Labirint al Oportunităților. Acest covor este conceput pentru a intra în afaceri complexe și a scăpa de situații dificile. Pare imposibil să scapi de soarte încâlcite, cazuri încâlcite și matrici complexe, dar acest covor arată că o persoană este un labirint. Covorul este conceput pentru a scăpa de situații foarte dificile și confuze din viață. 6.\nProtejează-mă în afaceri, în dragoste, învăluie-mă în veșminte invizibile, astfel încât dușmanii vizibili și invizibili să nu mă observe. Acest covor gri va dezvălui planurile manipulatorului. Culoarea fericirii îl va învălui imperceptibil pe oricine îl cumpără.\n', '', 1, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, '', 'PsyGeometry'),
(4, 33, 'Mocheta Dreptunghiulara 4', 0, 160.00, 100.00, 'Image3.png', 'Runarium. Simbolurile runice sunt destinate succesului în lumea financiară și lucrului cu colegi buni.\nRunica este compusă din 9 rune. Acestea conțin un cod ascuns al norocului pentru oricine îndrăznește să-l aducă la viață la birou, acasă sau oriunde altundeva este atât de necesară.\nCumpără o picătură, un covor miraculos și nu vei regreta banii, iar toată lumea are nevoie de succes financiar la locul de muncă.\n', NULL, 1, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, '', 'PsyGeometry'),
(6, 34, 'Mocheta Dreptunghiulara 6', 0, 160.00, 100.00, 'Image4.png', 'Protejează-mă în afaceri, în dragoste, învăluie-mă în veșminte invizibile, astfel încât dușmanii vizibili și invizibili să nu mă observe. Acest covor gri va dezvălui planurile manipulatorului. Culoarea fericirii îl va învălui imperceptibil pe oricine îl cumpără.', '', 1, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, '', 'PsyGeometry'),
(7, 35, 'Mocheta Dreptunghiulara 7', 0, 160.00, 100.00, 'Image5.png', 'Ziua este foarte aproape când sănătatea și protecția împotriva bolilor mintale vor intra în casa numită trupul meu. Sănătatea minții și a trupului, puterea Zeității ascunse care învăluie icoanele cu credință, speranță și iubire. Formele psihogeometrice afectează pietrele, plasticul și sticla din casă. Metalul și oxizii metalici. Dacă există plante sau flori, acestea vor fi umplute de puterea acestui covor. Astfel, o persoană își va îmbunătăți bunăstarea.', '', 1, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, '', 'PsyGeometry'),
(8, 36, 'Mocheta Dreptunghiulara 8', 0, 160.00, 100.00, 'Image6.png', 'Tot ce are legătură cu munca și dorințele tale în această muncă este conținut în trei simboluri și în această formă psihogeometrică. Acest covor talisman rezolvă și ajută la rezolvarea problemelor periculoase la locul de muncă.\n\nDezvăluie secretul celor care îl ascund. Ajută în multe probleme.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(9, 37, 'Mocheta Dreptunghiulara 9', 0, 160.00, 100.00, 'Image7.png', 'Acest covor conține multe secrete. Ascunde secretele oamenilor și ale zeilor care sporesc abilitățile umane. Simbolismul și geometria lor, în numeroasele lor forme energo-informaționale, oferă oamenilor oportunități minunate de a se descoperi acolo unde este nevoie. Acest covor conține secretele lumii. Cumpără, deschide și folosește.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(10, 38, 'Mocheta Dreptunghiulara 10', 0, 160.00, 100.00, 'Image8.png', 'Runascript, runestav, labirint runic sub formă de mandală. Acest secret runic este un asistent în afaceri, în încheierea contractelor, în descoperirea conspirațiilor. Galbenul este comunicarea, un aliat, un secretar, un consilier, comunicarea cu diferite tipuri de oameni pentru a rezolva problemele legate de muncă. Finanțele și bogăția sunt scopul său final. Dar fiecare covor conține puterea invizibilă a lui Dumnezeu, Creatorul a toate. Ia-l, cumpără-l și bucură-te că ai putut atinge secretele problemelor invizibile.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 39, 'Mocheta Dreptunghiulara 11', 0, 160.00, 100.00, 'Image9.png', 'Compoziție din 3 sigilii: unește puterea pentru service, afacere, clientelă bună, foarte bun la vânzarea produselor, de asemenea are protecție împotriva hoților fizici sau energetici. Forma de cruce face stabilitate. ', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 40, 'Mocheta Dreptunghiulara 12', 0, 160.00, 100.00, 'Image10.png', 'Talisman realizat din compoziția a 9 runascripte. Potențează oricare dorință pentru realizarea ei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 41, 'Mocheta Dreptunghiulara 13', 0, 160.00, 100.00, 'Image11.png', 'Talisman pentru familie, iubire, copii; aceste forme arcuite au în structură milioane tipuri de cuvinte de putere, mantre, rugăciuni și puterea îngerilor. ', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 42, 'Mocheta Dreptunghiulara 14', 0, 160.00, 100.00, 'Image12.png', ' În fața Sfintei Treimi a fost creată o formă vie, pentru conducerea oricărei forme de bogăție. Este un mare talisman care, împreună cu puterea divină, ajută să fi bogat, iar dacă e nevoie, în mod secret. Abundență.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 43, 'Mocheta Dreptunghiulara 15', 0, 160.00, 100.00, 'Image13.png', 'Psihogeometria sacră și numerologia secretă unește codurile cu tot ceea ce își poate dori un om în viață. ', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 44, 'Mocheta Dreptunghiulara 16', 0, 160.00, 100.00, 'Image14.png', 'Armonie în cuplu, pentru familie, armonie și pace în casă, ajută tinerilor care își doresc să facă un cuplu.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 45, 'Mocheta Dreptunghiulara 17', 0, 160.00, 100.00, 'Image15.png', 'Rezolvarea situațiilor legate de partea financiară: datorii, rate la bancă, împrumuturi etc.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 46, 'Mocheta Dreptunghiulara 18', 0, 160.00, 100.00, 'Image16.png', 'Puterea din sigiliul îngerului protector. Ghidează și protejează de aripile invizibile ale acestui înger. Îngerul este imparțial ', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 47, 'Mocheta Dreptunghiulara 19', 0, 160.00, 100.00, 'Image17.png', 'Numele Lui Dumnezeu reflectează în oricare celulă a corpului. Sunetul este HRI. Vindecare, protecție, regenerare, echilibru. Mandala HRI și mantra, are legătură cu numele Hristos din vechea limbă greacă. În Himalaya monograma HRI este centrul lotusului vieții pe care stă Creatorul.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 48, 'Mocheta Dreptunghiulara 20', 0, 160.00, 100.00, 'Image18.png', 'Mandala artefact a Serafimului Elemiah, cel care ajută la succesul professional, spiritul antreprenorial, stabilitate financiară și protejează în călătorii.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 49, 'Mocheta Dreptunghiulara 21', 0, 160.00, 100.00, 'Image19.png', 'Mandala cu Serafimul Mahasiah, cel care promovează înțelegerea, toleranța și abilitatea de a trăi în pace cu lumea, susține învățarea, știința și înțelegerea simbolisticii din mesajele viselor.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 50, 'Mocheta Dreptunghiulara 22', 0, 160.00, 100.00, 'Image20.png', 'Puterea zeilor, a divinităților, Sfintei Treimi. Mare artefact cu mandale, semnături, simboluri, psihogeometrie pentru tot ceea ce îi poate dori un om în viața lui. Se activează cu mantra HRI', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 51, 'Mocheta Dreptunghiulara 23', 0, 160.00, 100.00, 'Image21.png', 'Puterea divinităților în forme diferite, este și în acest minunat covor. Iubire, sănătate, prosperitate, protecție, îndrumare divină, acestea sunt câteva dintre beneficiile acestui artefact complex.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 52, 'Mocheta Dreptunghiulara 24', 0, 160.00, 100.00, 'Image22.png', 'Mocheta artefact pentru rezolvarea situațiilor complicate atât în familie cât și la servici sau în societate. Fericire și success împreună cu iluminare înmulțește puterea în oricare fie personal fie comun.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 53, 'Mocheta Dreptunghiulara 25', 0, 160.00, 100.00, 'Image23.png', 'Un nexus biocibernetic de formule runice și o structură sigilistică au conectat ușor un câmp țesut dintr-o multitudine de formule în jurul unei idei centrale. Tot ce și-ar putea dori cineva este conținut în acest desen mistic. Rugăciuni, mantre, nume de zei, rune, sigilii, nume de îngeri, formule pentru vindecarea bolilor complexe, soluții la dificultăți financiare - întregul câmp al miracolelor a unit 2.000 de structuri sinusoidale psihogeometrice și numerologice. Un generator, o forță.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 54, 'Mocheta Dreptunghiulara 26', 0, 160.00, 100.00, 'Image24.png', 'Acest model roșu închis conectează două personalități divine, Lakshmi și Narayana. Ele sunt ca mierea pentru viața de pe planeta noastră. Dragostea și puterea lor ajută în multe demersuri.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 55, 'Mocheta Dreptunghiulara 27', 0, 160.00, 100.00, 'Image25.png', 'Nu poți fi prins când ideea ta devine realitate. Acest talisman sporește abilitățile și te ajută să iei ceea ce este cel mai necesar dintr-o idee, o fantezie sau un plan virtual și să-l aduci la viață. Îndrăznește și ia-l. Este asistentul tău în ideile și realizările tale.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 56, 'Mocheta Dreptunghiulara 28', 0, 160.00, 100.00, 'Image26.png', 'Există întotdeauna o putere angelică invizibilă în toate demersurile. Codul îngeresc și numele său, Yeliel, sunt o adevărată forță invizibilă atât în afaceri, cât și în armonia vetrei familiei.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 57, 'Mocheta Dreptunghiulara 29', 0, 160.00, 100.00, 'Image27.png', ' Un adevărat artefact al forțelor naturale ale Zeilor și ale Creatorului însuși. Mandalele personalităților divine și fire aurii și galbene îți vor învălui ideile și le vor aduce la viață. \n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 58, 'Mocheta Dreptunghiulara 30', 0, 160.00, 100.00, 'Image28.png', 'Un artefact al destinului și al puterii timpului sunt unite în acest ansamblu. Câteva mii de coduri divine într-un singur loc. Micile mandale din stânga și din dreapta reprezintă rugăciunea noastră, Rugăciunea Domnească, iar în centru, un adevărat scut te protejează de pericolele sorții.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 59, 'Mocheta Dreptunghiulara 31', 0, 160.00, 100.00, 'Image29.png', 'Cărțile antice vorbesc despre corăbii inscripționate cu anumite semne. Iată două sigilii. În partea de sus se află un sigiliu care protejează de hoți și tâlhari. În partea de jos se află un semn, un sigiliu care îndepărtează cu blândețe energia rea dintr-o persoană, o vrajă. Curăță și îmbunătățește aura și psihicul. Curăță de energia negativă. Împreună, aceste sigilii ajută pe cineva să se elibereze de negativitate și de oamenii răi.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 60, 'Mocheta Dreptunghiulara 32', 0, 160.00, 100.00, 'Image30.png', 'Putere protectoare enormă. Se numește HAGISPER. În orice situație dificilă, provocatoare, este un ajutor. Geometria sa salvează de situațiile rele. Eliberează calea și îmbunătățește viața și situațiile unei persoane.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 61, 'Mocheta Dreptunghiulara 33', 0, 160.00, 100.00, 'Image31.png', 'Un artefact derivat din himalayană, tibetană, sanscrită și din propriile noastre rugăciuni și mantre. Conține energia a câteva zeci de coduri psihogeometrice și simboluri numerologice, transformate în puterile ființelor divine. Este perfect pentru casă și birou, pentru copii și adulți. Acest artefact conectează destinele și puterile Sfintei Treimi și pe cei care le sunt fideli, atât în dragoste, cât și în afaceri, precum și în soluții creative. Universul aude și vede și te ajută în viață.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 62, 'Mocheta Dreptunghiulara 34', 0, 160.00, 100.00, 'Image32.png', 'Labirint psihogeometric al puterii îngerului Elemiah. Un asistent în viață, în multe privințe.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 63, 'Mocheta Dreptunghiulara 35', 0, 160.00, 100.00, 'Image33.jpg', 'Este dificil să găsești persoana potrivită pentru muncă, pentru viață, pentru dragoste, pentru prietenie adevărată. Iată-l. Acest artefact te conectează cu cel pe care ți-ai dori să-l vezi alături.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 64, 'Mocheta Dreptunghiulara 36', 0, 160.00, 100.00, 'Image34.jpg', 'Acest mic miracol este creat dintr-o mantră a norocului. Aceasta este puterea sa. Noroc și avere în afaceri și în necazurile vieții.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 65, 'Mocheta Dreptunghiulara 37', 0, 160.00, 100.00, 'Image35.png', 'Dacă ceva este ascuns, există un secret, dacă trebuie să găsești ceva sau pe cineva, acest artefact te va ajuta. Ia-l și verifică-l singur. Dar nu-l folosi de prea multe ori odată. Și oricine este ascuns în această imagine are nevoie de odihnă și acumulare de forță pentru data viitoare. Ajută la găsirea a ceea ce este ascuns la nivel fizic, mental și intelectual.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 66, 'Mocheta Dreptunghiulara 38', 0, 160.00, 100.00, 'Image36.png', 'Când Matricea te absoarbe, acest artefact te salvează. O gură de oxigen de la manipularea conștiinței tale.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 67, 'Mocheta Dreptunghiulara 39', 0, 160.00, 100.00, 'Image37.png', 'Dacă cineva te deranjează, această imagine nu este simplă. Te va curăța de negativitate, îți va îmbunătăți sănătatea, te va ajuta să găsești un asistent și te va proteja atât pe drum, cât și oriunde. Acest artefact conține multe rugăciuni și mantre. Modelele lor psihogeometrice formează un câmp energetic invizibil pe mulți kilometri.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 68, 'Mocheta Dreptunghiulara 40', 0, 160.00, 100.00, 'Image38.png', 'Crește puterea pentru sarcina la îndemână. Oferă putere pentru dorință. Labirintul său este țesut din fire. Aceste noduri de fire creează energia necesară pentru ceea ce este dorit. Ajută plantele, animalele și oamenii.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 69, 'Mocheta Dreptunghiulara 41', 0, 160.00, 100.00, 'Image39.png', 'Un semn secret unic al civilizației lor orientale antice. Secretul său dezvăluie secrete ascunse în pământ și în oameni. Ajută în sate, la locul de muncă și pe drum.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1, 70, 'Mocheta Dreptunghiulara 1', 0, 160.00, 100.00, 'Image40.png', 'Conexiunea liniilor ondulate reprezintă uniunea a două persoane. Pe un fundal albastru, reprezintă libertatea în relații, dar și credința în unitate. Formele în formă de cruce roșie reprezintă dezvăluirea secretelor în familie și la locul de muncă.', '', 1, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, '', 'PsyGeometry'),
(1000, 71, 'Mocheta Dreptunghiulara 42', 0, 160.00, 100.00, 'Image41.png', ' Peste 2 milioane de microstructuri psihogeometrice, numerologice și matriceale sunt combinate în acest artefact. Pentru noroc, sănătate și iluminare. Tot ce este în întuneric va fi iluminat și vizibil. Îmbunătățește superputerile. Crește puterea și rezistența. Numeroase rugăciuni, cuvinte, mantre și simboluri sunt combinate în acest spațiu multidimensional, unite în această pictură, în acest artefact.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 72, 'Mocheta Dreptunghiulara 43', 0, 160.00, 100.00, 'Image42.png', 'Runa URUZ, un ajutor minunat în deblocarea capacității de a rezolva probleme complexe.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 73, 'Mocheta Dreptunghiulara 44', 0, 160.00, 100.00, 'Image43.png', '2 glife - semnături ale puterii și 1 formulă de scriere runică. Pentru tranzacții financiare. Pentru muncă. Ajută în treburile unei companii sau asociații. Bun pentru fabrici și uzine. Este bun dacă este pe o mașină. Ajută pe oricine să dezvolte puterea de a conduce proiecte mici și mari. Această putere permite 100% muncă.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 74, 'Mocheta Dreptunghiulara 45', 0, 160.00, 100.00, 'Image44.png', 'Putere angelică enormă. Ajută acolo unde pare să nu existe putere. Va da putere și va ajuta la ieșirea din situații periculoase. Va îmbunătăți sănătatea și va da putere.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 75, 'Mocheta Dreptunghiulara 46', 0, 160.00, 100.00, 'Image45.png', 'Un artefact mare ajutor. În yum, rugăciunile și mantrele sunt combinate într-unul singur. Pentru cei cărora le place să își asume riscuri și să câștige. Pentru victorie.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 76, 'Mocheta Dreptunghiulara 47', 0, 160.00, 100.00, 'Image46.png', 'Toate cuvintele Psalmului 22 sunt traduse în numere, iar aceste numere sunt traduse în psihogeometrie. Psalmul 22 te va salva și te va ajuta în viață.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 77, 'Mocheta Dreptunghiulara 48', 0, 160.00, 100.00, 'Image47.png', 'Uneori pare că totul în familia ta este exact așa cum îți dorești. Dar nu este adevărat. Toate planetele și stelele au propriul lor loc spațial personal. Acest soare te va încălzi și te va ajuta să te simți mai apropiat de cei pe care îi iubești.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 78, 'Mocheta Dreptunghiulara 49', 0, 160.00, 100.00, 'Image48.png', 'Yantra plane in cifre', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 79, 'Mocheta Dreptunghiulara 50', 0, 160.00, 100.00, 'Image49.png', 'Frica este atunci când nu poți să-ți dai seama de unde provine. Dar dacă o faci? Această formă este foarte magică; te ajută să accepți frica ca o forță care te schimbă și îți oferă o oportunitate reală de a transforma frica în curaj. Iubește și înțelege cum să nu depășești frica, ci să o modifici, să o purifici și să o folosești pentru casă, familie, muncă și atingerea obiectivelor tale.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 80, 'Mocheta Dreptunghiulara 51', 0, 160.00, 100.00, 'Image50.png', 'Există o putere unică pentru rezolvarea problemelor și primirea ajutorului de la Dumnezeul triunic. Are o formă și un suflet în ea. Aceasta este o altă parte a lui Dumnezeu. Numele său este Kubera. El îți va veni întotdeauna în ajutor dacă ai probleme cu finanțele, banii sau bogăția. Dorința de bogăție vine de la slujitorul lui Dumnezeu, din partea sa, al cărui nume este Kubera. Acest artefact ajută la muncă, documente, bani și autocontrol. 52 - Acesta nu este doar un labirint; conține o conexiune psihogeometrică ce îți va îmbunătăți bunăstarea și sănătatea. Acest labirint de linii și noduri conține un secret numerologic și psihogeometric ascuns, puterea lui Dumnezeu și puterea minții care te purifică pe tine și pe cei care intră în contact cu tine și cu această imagine.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 81, 'Mocheta Dreptunghiulara 52', 0, 160.00, 100.00, 'Image51.png', 'Acesta nu este doar un labirint; conține o conexiune psihogeometrică ce îți va îmbunătăți bunăstarea și sănătatea. Acest labirint de linii și noduri conține un secret numerologic și psihogeometric ascuns, puterea lui Dumnezeu și puterea minții care te purifică pe tine și pe cei care intră în contact cu tine și cu această imagine.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 82, 'Mocheta Dreptunghiulara 53', 0, 160.00, 100.00, 'Image52.png', 'Zeii și Zeițele sunt ajutoare de la Dumnezeu, de la Creator, de la Duhul Sfânt. Sunt mulți dintre ei. Îngerii și sfinții din toate religiile lumii sunt el, ochii, mâinile, urechile sale, gustul și mirosul său. Care imagine sinusoidală a personalității divine va ajuta acolo unde pare să nu existe nicio ieșire? Un artefact pentru rezolvarea dificultăților atât în ​​sănătate, cât și în viață.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 83, 'Mocheta Dreptunghiulara 54', 0, 160.00, 100.00, 'Image53.png', 'Un nod foarte complex al vieții poate fi dezlegat doar de cel care l-a legat. Karma și soarta sunt controlate de cineva. Așadar, EL sau EA te vor ajuta să dezlegi nodurile cosmice, astrologice și fatidice ale vieții tale. 55 - Când familia sau rudele tale au nevoie de ordine, acest artefact va ajuta la îmbunătățirea ei. Puterea angelică și mâna invizibilă a lui Dumnezeu vor intra în casa ta și te vor ajuta în relațiile tale cu prietenii, familia și cei dragi.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 84, 'Mocheta Dreptunghiulara 55', 0, 160.00, 100.00, 'Image54.png', '\nCând familia sau rudele tale au nevoie de ordine, acest artefact te va ajuta să o îmbunătățești. Puterea angelică și mâna invizibilă a lui Dumnezeu vor intra în casa ta și te vor ajuta în relațiile cu prietenii, familia și cei dragi.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 85, 'Mocheta Dreptunghiulara 56', 0, 160.00, 100.00, 'Image55.png', 'Există multe secrete pe pământ. Acesta este secretul sigiliilor. Aceste semne puternice ale puterii au ajuns la noi din diferite civilizații. Sunt folosite în multe scopuri diferite pe pământ. Sunt ca o unealtă. În mâinile unei persoane întunecate, sunt periculoase, dar în mâinile unei persoane strălucitoare, sunt un miracol pentru tot ceea ce și-ar putea dori cineva. Fiecare sigiliu este foarte important. De-a lungul a sute de ani, aceste semne nu și-au pierdut moei-ul și puterea.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 86, 'Mocheta Dreptunghiulara 57', 0, 160.00, 100.00, 'Image56.png', 'Când o persoană are nevoie de abilități, competențe sau superputeri, această imagine o ajută să le dobândească. Aceasta este puterea cuvintelor în formă și forma în ceea ce vezi. Privește asta pentru un minut și, dacă este un covor, mergi pe el și gândește-te la ce ai nevoie. Aceasta este magia divină a cuvintelor sub forma unei mandale.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 87, 'Mocheta Dreptunghiulara 58', 0, 160.00, 100.00, 'Image57.png', 'Mandala Îngerească. Vei fi protejat și, dacă este necesar, vei deveni vizibil sau invizibil pentru toată lumea. Această mandală, pe un fundal de cer albastru, dezvăluie secretele naturii, atât umane, cât și pământești. Caută și găsește.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 88, 'Mocheta Dreptunghiulara 59', 0, 160.00, 100.00, 'Image58.jpg', 'Mandala Îngerească este un protector și un ajutor în viața ta. Aceste modele au fost create personal. Conțin codul și puterea îngerului. Este frumoasă pentru casă, familie sau birou. Și este foarte bună pentru vindecare și vindecare atât fizică, cât și mentală.\n', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 89, 'Mocheta Dreptunghiulara 60', 0, 160.00, 100.00, 'Image59.png', ' Când simți că nu poți trece o linie, când nu ești auzit sau înțeles, când îți dorești atât bani, cât și respect, această imagine puternică îți va da putere, curaj și capacitatea de a depăși obstacolele și de a realiza ceea ce pare imposibil. Codul angelic numerologic și psihogeometric sub forma acestei structuri nodale îți va oferi acest lucru. Un artefact minunat de ajutor și putere angelică divină.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 90, 'Mocheta Dreptunghiulara 61', 0, 160.00, 100.00, 'Image60.png', 'Atunci când simți că ai ajuns la limită, că vocea ta nu este auzită și că drumul din fața ta pare blocat, această imagine puternică îți poate aduce încredere, echilibru și forța de a merge mai departe. Prin simbolistica sa numerologică și geometrică, această structură nodală transmite energie, protecție și susținere interioară. Este un artefact deosebit, creat pentru a inspira curaj, putere și depășirea obstacolelor.', NULL, 0, '2026-02-18 08:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(-1000, 91, 'Ingeras 1', 6, 5.00, 2.00, 'Image61.png', 'Îngerul Păcii este prevăzut cu agățătoare din turnare. Este turnat din ipsos de modelaj și apă, in sistem handmade. \nȘtim că Îngerii sunt ajutoare de lumină ce ne susțin mereu! Eu sunt cei care ne transmit gândul bun și Pacea! 💕', NULL, 124, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Ingerasi'),
(0, 92, 'Ingeras 2', 6, 5.00, 2.00, 'Image62.png', 'Îngerul Păcii este prevăzut cu agățătoare din turnare. Este turnat din ipsos de modelaj și apă, in sistem handmade. \nȘtim că Îngerii sunt ajutoare de lumină ce ne susțin mereu! Eu sunt cei care ne transmit gândul bun și Pacea! 💕', NULL, 10, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00, NULL, 'Ingerasi'),
(0, 93, 'Ingeras 3', 6, 5.00, 2.00, 'Image63.png', 'Îngerul Păcii este prevăzut cu agățătoare din turnare. Este turnat din ipsos de modelaj și apă, in sistem handmade. \nȘtim că Îngerii sunt ajutoare de lumină ce ne susțin mereu! Eu sunt cei care ne transmit gândul bun și Pacea! 💕', NULL, 10, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00, NULL, 'Ingerasi'),
(0, 94, 'Ingeras 4', 6, 5.00, 2.00, 'Image64.png', 'Îngerul Păcii este prevăzut cu agățătoare din turnare. Este turnat din ipsos de modelaj și apă, in sistem handmade. \nȘtim că Îngerii sunt ajutoare de lumină ce ne susțin mereu! Eu sunt cei care ne transmit gândul bun și Pacea! 💕', NULL, 10, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00, NULL, 'Ingerasi'),
(0, 95, 'Ingeras 5', 6, 5.00, 2.00, 'Image65.png', 'Îngerul Păcii este prevăzut cu agățătoare din turnare. Este turnat din ipsos de modelaj și apă, in sistem handmade. \nȘtim că Îngerii sunt ajutoare de lumină ce ne susțin mereu! Eu sunt cei care ne transmit gândul bun și Pacea! 💕', NULL, 10, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00, NULL, 'Ingerasi'),
(1000, 100, 'Mandala 1', 6, 0.00, 0.00, 'Image71.png', 'Contine:magnet,plastic.\nA nu se lasa la indemana copiilor sub 3 ani.', NULL, 10, '2026-02-23 09:54:20', 1, NULL, NULL, 6.00, NULL, 'Mandala'),
(1000, 101, 'Mandala 2', 6, 0.00, 0.00, 'Image72.png', 'Contine:magnet,plastic.\nA nu se lasa la indemana copiilor sub 3 ani.', NULL, 10, '2026-02-23 07:54:20', 1, NULL, NULL, 6.00, NULL, 'Mandala'),
(1000, 102, 'Mandala 3', 6, 0.00, 0.00, 'Image73.png', 'Contine:magnet,plastic.\nA nu se lasa la indemana copiilor sub 3 ani.', NULL, 10, '2026-02-23 05:54:20', 1, NULL, NULL, 6.00, NULL, 'Mandala'),
(1000, 103, 'Mandala 4', 6, 0.00, 0.00, 'Image74.png', 'Contine:magnet,plastic.\nA nu se lasa la indemana copiilor sub 3 ani.', NULL, 10, '2026-02-23 05:54:20', 1, NULL, NULL, 6.00, NULL, 'Mandala'),
(1000, 111, 'Tablou 1', 0, 42.00, 30.00, 'Image81.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 11:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 112, 'Tablou 2', 0, 42.00, 30.00, 'Image82.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 11:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 113, 'Tablou 3', 0, 42.00, 30.00, 'Image83.png', 'Glifele - semnături ale puterilor angelice, sigilii din cărți secrete despre puterile ființelor angelice și celeste, mandale ale rugăciunilor și mantrelor, conferă acestui covor modelele sale unice. Acest covor-artefact este ca un talisman pentru noroc, fericire și sănătate în destinul oricui îndrăznește să-l ia în casa, apartamentul sau biroul său.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 114, 'Tablou 4', 0, 42.00, 30.00, 'Image84.png', 'O lucrare personală a autorului, Sergey Danshin. Un Labirint al Oportunităților. Acest covor este conceput pentru a intra în afaceri complexe și a scăpa de situații dificile. Pare imposibil să scapi de soarte încâlcite, cazuri încâlcite și matrici complexe, dar acest covor arată că o persoană este un labirint. Covorul este conceput pentru a scăpa de situații foarte dificile și confuze din viață. 6.\nProtejează-mă în afaceri, în dragoste, învăluie-mă în veșminte invizibile, astfel încât dușmanii vizibili și invizibili să nu mă observe. Acest covor gri va dezvălui planurile manipulatorului. Culoarea fericirii îl va învălui imperceptibil pe oricine îl cumpără.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 115, 'Tablou 5', 0, 42.00, 30.00, 'Image85.png', 'Runarium. Simbolurile runice sunt destinate succesului în lumea financiară și lucrului cu colegi buni.\nRunica este compusă din 9 rune. Acestea conțin un cod ascuns al norocului pentru oricine îndrăznește să-l aducă la viață la birou, acasă sau oriunde altundeva este atât de necesară.\nCumpără o picătură, un covor miraculos și nu vei regreta banii, iar toată lumea are nevoie de succes financiar la locul de muncă.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 116, 'Tablou 6', 0, 42.00, 30.00, 'Image86.png', 'Tot ce are legătură cu munca și dorințele tale în această muncă este conținut în trei simboluri și în această formă psihogeometrică. Acest covor talisman rezolvă și ajută la rezolvarea problemelor periculoase la locul de muncă.\n\nDezvăluie secretul celor care îl ascund. Ajută în multe probleme.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 117, 'Tablou 7', 0, 42.00, 30.00, 'Image87.png', 'Acest covor conține multe secrete. Ascunde secretele oamenilor și ale zeilor care sporesc abilitățile umane. Simbolismul și geometria lor, în numeroasele lor forme energo-informaționale, oferă oamenilor oportunități minunate de a se descoperi acolo unde este nevoie. Acest covor conține secretele lumii. Cumpără, deschide și folosește.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 118, 'Tablou 8', 0, 42.00, 30.00, 'Image88.png', 'Compoziție din 3 sigilii: unește puterea pentru service, afacere, clientelă bună, foarte bun la vânzarea produselor, de asemenea are protecție împotriva hoților fizici sau energetici. Forma de cruce face stabilitate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 119, 'Tablou 9', 0, 42.00, 30.00, 'Image89.png', 'Talisman pentru familie, iubire, copii; aceste forme arcuite au în structură milioane tipuri de cuvinte de putere, mantre, rugăciuni și puterea îngerilor.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 120, 'Tablou 10', 0, 42.00, 30.00, 'Image90.png', 'În fața Sfintei Treimi a fost creată o formă vie, pentru conducerea oricărei forme de bogăție. Este un mare talisman care, împreună cu puterea divină, ajută să fi bogat, iar dacă e nevoie, în mod secret. Abundență.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 121, 'Tablou 11', 0, 42.00, 30.00, 'Image91.png', 'Armonie în cuplu, pentru familie, armonie și pace în casă, ajută tinerilor care își doresc să facă un cuplu.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 122, 'Tablou 12', 0, 42.00, 30.00, 'Image92.png', 'Rezolvarea situațiilor legate de partea financiară: datorii, rate la bancă, împrumuturi etc.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 123, 'Tablou 13', 0, 42.00, 30.00, 'Image93.png', 'Puterea din sigiliul îngerului protector. Ghidează și protejează de aripile invizibile ale acestui înger. Îngerul este imparțial', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 124, 'Tablou 14', 0, 42.00, 30.00, 'Image94.png', 'Mandala artefact a Serafimului Elemiah, cel care ajută la succesul professional, spiritul antreprenorial, stabilitate financiară și protejează în călătorii.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 125, 'Tablou 15', 0, 42.00, 30.00, 'Image95.png', 'Mandala cu Serafimul Mahasiah, cel care promovează înțelegerea, toleranța și abilitatea de a trăi în pace cu lumea, susține învățarea, știința și înțelegerea simbolisticii din mesajele viselor.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 126, 'Tablou 16', 0, 42.00, 30.00, 'Image96.png', 'Puterea zeilor, a divinităților, Sfintei Treimi. Mare artefact cu mandale, semnături, simboluri, psihogeometrie pentru tot ceea ce îi poate dori un om în viața lui. Se activează cu mantra HRI', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 127, 'Tablou 17', 0, 42.00, 30.00, 'Image97.png', 'Puterea divinităților în forme diferite, este și în acest minunat covor. Iubire, sănătate, prosperitate, protecție, îndrumare divină, acestea sunt câteva dintre beneficiile acestui artefact complex.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 128, 'Tablou 18', 0, 42.00, 30.00, 'Image98.png', 'Un nexus biocibernetic de formule runice și o structură sigilistică au conectat ușor un câmp țesut dintr-o multitudine de formule în jurul unei idei centrale. Tot ce și-ar putea dori cineva este conținut în acest desen mistic. Rugăciuni, mantre, nume de zei, rune, sigilii, nume de îngeri, formule pentru vindecarea bolilor complexe, soluții la dificultăți financiare - întregul câmp al miracolelor a unit 2.000 de structuri sinusoidale psihogeometrice și numerologice. Un generator, o forță.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 129, 'Tablou 19', 0, 42.00, 30.00, 'Image99.png', 'Un adevărat artefact al forțelor naturale ale Zeilor și ale Creatorului însuși. Mandalele personalităților divine și fire aurii și galbene îți vor învălui ideile și le vor aduce la viață.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 130, 'Tablou 20', 0, 42.00, 30.00, 'Image100.png', 'Un artefact al destinului și al puterii timpului sunt unite în acest ansamblu. Câteva mii de coduri divine într-un singur loc. Micile mandale din stânga și din dreapta reprezintă rugăciunea noastră, Rugăciunea Domnească, iar în centru, un adevărat scut te protejează de pericolele sorții.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 131, 'Tablou 21', 0, 42.00, 30.00, 'Image101.png', 'Labirint psihogeometric al puterii îngerului Elemiah. Un asistent în viață, în multe privințe.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 132, 'Tablou 22', 0, 42.00, 30.00, 'Image102.png', 'Când Matricea te absoarbe, acest artefact te salvează. O gură de oxigen de la manipularea conștiinței tale.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 133, 'Tablou 23', 0, 42.00, 30.00, 'Image103.png', 'Dacă cineva te deranjează, această imagine nu este simplă. Te va curăța de negativitate, îți va îmbunătăți sănătatea, te va ajuta să găsești un asistent și te va proteja atât pe drum, cât și oriunde. Acest artefact conține multe rugăciuni și mantre. Modelele lor psihogeometrice formează un câmp energetic invizibil pe mulți kilometri.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 134, 'Tablou 24', 0, 42.00, 30.00, 'Image104.png', 'Crește puterea pentru sarcina la îndemână. Oferă putere pentru dorință. Labirintul său este țesut din fire. Aceste noduri de fire creează energia necesară pentru ceea ce este dorit. Ajută plantele, animalele și oamenii.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 135, 'Tablou 25', 0, 42.00, 30.00, 'Image105.png', 'Un semn secret unic al civilizației lor orientale antice. Secretul său dezvăluie secrete ascunse în pământ și în oameni. Ajută în sate, la locul de muncă și pe drum.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 136, 'Tablou 26', 0, 42.00, 30.00, 'Image106.png', 'Conexiunea liniilor ondulate reprezintă uniunea a două persoane. Pe un fundal albastru, reprezintă libertatea în relații, dar și credința în unitate. Formele în formă de cruce roșie reprezintă dezvăluirea secretelor în familie și la locul de muncă.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 137, 'Tablou 27', 0, 42.00, 30.00, 'Image107.png', 'Toate cuvintele Psalmului 22 sunt traduse în numere, iar aceste numere sunt traduse în psihogeometrie. Psalmul 22 te va salva și te va ajuta în viață.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 138, 'Tablou 28', 0, 42.00, 30.00, 'Image108.png', 'Acesta nu este doar un labirint; conține o conexiune psihogeometrică ce îți va îmbunătăți bunăstarea și sănătatea. Acest labirint de linii și noduri conține un secret numerologic și psihogeometric ascuns, puterea lui Dumnezeu și puterea minții care te purifică pe tine și pe cei care intră în contact cu tine și cu această imagine.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 139, 'Tablou 29', 0, 42.00, 30.00, 'Image109.png', 'Un nod foarte complex al vieții poate fi dezlegat doar de cel care l-a legat. Karma și soarta sunt controlate de cineva. Așadar, EL sau EA te vor ajuta să dezlegi nodurile cosmice, astrologice și fatidice ale vieții tale. 55 - Când familia sau rudele tale au nevoie de ordine, acest artefact va ajuta la îmbunătățirea ei. Puterea angelică și mâna invizibilă a lui Dumnezeu vor intra în casa ta și te vor ajuta în relațiile tale cu prietenii, familia și cei dragi.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 140, 'Tablou 30', 0, 42.00, 30.00, 'Image110.png', 'Când familia sau rudele tale au nevoie de ordine, acest artefact te va ajuta să o îmbunătățești. Puterea angelică și mâna invizibilă a lui Dumnezeu vor intra în casa ta și te vor ajuta în relațiile cu prietenii, familia și cei dragi.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 141, 'Tablou 31', 0, 42.00, 30.00, 'Image111.png', 'Mandala cu Serafimul Mahasiah, cel care promovează înțelegerea, toleranța și abilitatea de a trăi în pace cu lumea, susține învățarea, știința și înțelegerea simbolisticii din mesajele viselor.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 142, 'Tablou 32', 0, 42.00, 30.00, 'Image112.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 143, 'Tablou 33', 0, 42.00, 30.00, 'Image113.png', 'Atunci când simți că ai ajuns la limită, că vocea ta nu este auzită și că drumul din fața ta pare blocat, această imagine puternică îți poate aduce încredere, echilibru și forța de a merge mai departe. Prin simbolistica sa numerologică și geometrică, această structură nodală transmite energie, protecție și susținere interioară. Este un artefact deosebit, creat pentru a inspira curaj, putere și depășirea obstacolelor.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 144, 'Tablou 34', 0, 42.00, 30.00, 'Image114.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 145, 'Tablou 35', 0, 42.00, 30.00, 'Image115.png', 'Peste 2 milioane de microstructuri psihogeometrice, numerologice și matriceale sunt combinate în acest artefact. Pentru noroc, sănătate și iluminare. Tot ce este în întuneric va fi iluminat și vizibil. Îmbunătățește superputerile. Crește puterea și rezistența. Numeroase rugăciuni, cuvinte, mantre și simboluri sunt combinate în acest spațiu multidimensional, unite în această pictură, în acest artefact.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 146, 'Tablou 36', 0, 42.00, 30.00, 'Image116.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 147, 'Tablou 37', 0, 42.00, 30.00, 'Image117.png', 'Mocheta artefact pentru rezolvarea situațiilor complicate atât în familie cât și la servici sau în societate. Fericire și success împreună cu iluminare înmulțește puterea în oricare fie personal fie comun.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 148, 'Tablou 38', 0, 42.00, 30.00, 'Image118.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 149, 'Tablou 39', 0, 42.00, 30.00, 'Image119.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 150, 'Tablou 40', 0, 42.00, 30.00, 'Image120.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 151, 'Tablou 41', 0, 42.00, 30.00, 'Image121.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 152, 'Tablou 42', 0, 42.00, 30.00, 'Image122.png', 'Un tablou unic care te da pe spate.', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 153, 'Tablou 43', 0, 42.00, 30.00, 'Image123.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 154, 'Tablou 44', 0, 42.00, 30.00, 'Image124.png', 'Un tablou unic care te da pe spate', NULL, 0, '2026-02-23 09:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 155, 'Tablou 45', 0, 42.00, 30.00, 'Image125.png\r\n', 'Arhanghel Metatron și sigila-glif Moșek, sunt concepute pentru a ne oferi ajutor in viata. Energia acestui tablou Artefact schimba in bine campul energetic in casa, la birou si oriunde este asezat.', 'Arhanghel Metatron ajuta in tot ce facem', 0, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 156, 'Tablou 46', 0, 42.00, 30.00, 'Image126.png', 'Arhanghelul Metatron, a cărui prezență și putere sunt transformate în forme albastru deschis, în mandale cu un element roșu, reprezentând puterea succesului. Cinci forme în formă de cruce sigilate sunt destinate norocului la locul de muncă și atragerii persoanelor potrivite pentru a realiza ideile cuiva. În numerologie, un fundal verde reprezintă numărul 4, stabilitatea intenționatului în acțiune. Aceasta este puterea covorului.', NULL, 0, '2026-02-23 07:54:20', 1, NULL, NULL, 0.00, NULL, 'Tablouri'),
(1000, 161, 'Mocheta Rotunda PsyGeometry 1', 0, NULL, NULL, 'Image131.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 162, 'Mocheta Rotunda PsyGeometry 2', 0, NULL, NULL, 'Image132.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 163, 'Mocheta Rotunda PsyGeometry 3', 0, NULL, NULL, 'Image133.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 164, 'Mocheta Rotunda PsyGeometry 4', 0, NULL, NULL, 'Image134.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde');
INSERT INTO `products` (`sort_ordine`, `id`, `name`, `price`, `lungime_cm`, `latime_cm`, `img`, `description`, `preview`, `stock`, `created_at`, `active`, `updated_at`, `deleted_at`, `diameter_cm`, `material`, `category`) VALUES
(1000, 165, 'Mocheta Rotunda PsyGeometry 5', 0, NULL, NULL, 'Image135.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 166, 'Mocheta Rotunda PsyGeometry 6', 0, NULL, NULL, 'Image136.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 167, 'Mocheta Rotunda PsyGeometry 7', 0, NULL, NULL, 'Image137.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 168, 'Mocheta Rotunda PsyGeometry 8', 0, NULL, NULL, 'Image138.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 169, 'Mocheta Rotunda PsyGeometry 9', 0, NULL, NULL, 'Image139.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 170, 'Mocheta Rotunda PsyGeometry 10', 0, NULL, NULL, 'Image140.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 171, 'Mocheta Rotunda PsyGeometry 11', 0, NULL, NULL, 'Image141.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 172, 'Mocheta Rotunda PsyGeometry 12', 0, NULL, NULL, 'Image142.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 173, 'Mocheta Rotunda PsyGeometry 13', 0, NULL, NULL, 'Image143.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 174, 'Mocheta Rotunda PsyGeometry 14', 0, NULL, NULL, 'Image144.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 175, 'Mocheta Rotunda PsyGeometry 15', 0, NULL, NULL, 'Image145.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 176, 'Mocheta Rotunda PsyGeometry 16', 0, NULL, NULL, 'Image146.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 177, 'Mocheta Rotunda PsyGeometry 17', 0, NULL, NULL, 'Image147.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(1000, 178, 'Mocheta Rotunda PsyGeometry 18', 0, NULL, NULL, 'Image148.png', 'Elemiah este al 4-lea înger Kabbalistic din cei 72 de Shem HaMephorash, aparținând corului Serafimilor. Cunoscut ca Îngerul Puterii Interioare, Succesului și Protecției, Elemiah îi guvernează pe cei născuți între 5 și 9 aprilie. Acest înger inspiră noi începuturi, ajută la depășirea crizelor profesionale și oferă liniște și protecție în timpul călătoriilor.\n\n\nAspecte cheie ale Îngerului Elemiah:\n\nSemnificație: „Dumnezeu Ascuns” sau „Dumnezeu este Ascuns”.\n\nAtribute: Reprezintă succesul, protecția, puterea interioară și spiritul antreprenorial. Este considerat un planificator și un împăciuitor.\n\nZodiac/Element: 16°–20° în Berbec, elementul Focului.\n\nDate de naștere: 5 aprilie – 9 aprilie.\n\nDate de influență: 23 martie, 4 iunie, 16 august, 28 octombrie, 9 ianuarie.\n\nSimbolism: Adesea legat de Citrin, culorile auriu/indigo și este folosit pentru a dobândi cunoștințe despre trădători sau pentru a evita eșecurile în afaceri.\n\nSe crede că Elemiah ajută indivizii să își atingă obiectivele prin inițiativă și ajută la transformarea situațiilor dificile în rezultate favorabile.', '', 0, '2026-02-18 04:58:34', 1, NULL, NULL, 100.00, NULL, 'PsyGeometry Rotunde'),
(3, 182, 'Mocheta Dreptunghiulara 3', 0, 160.00, 100.00, 'Image150.png', 'Arhanghelul Metatron, a cărui prezență și putere sunt transformate în forme albastru deschis, în mandale cu un element roșu, reprezentând puterea succesului. Cinci forme în formă de cruce sigilate sunt destinate norocului la locul de muncă și atragerii persoanelor potrivite pentru a realiza ideile cuiva. În numerologie, un fundal verde reprezintă numărul 4, stabilitatea intenționatului în acțiune. Aceasta este puterea covorului.', NULL, 1, '2026-04-14 09:51:09', 1, NULL, NULL, 1.20, 'Mocheta printata prin sublimare, spate cauciuc antiderapant', 'PsyGeometry'),
(-1000, 190, 'Ingeras si mandala 1', 12, 5.00, 2.00, 'Image151.png', 'Contine:ipsos,magnet,plastic.\nA nu se lasa la indemana copiilor sub 3 ani.', 'Ingerasii sunt facuti cu materialul ipsos', 10, '2026-02-23 05:54:20', 1, NULL, NULL, 6.00, NULL, 'Ingerasi si mandale ale pacii'),
(1000, 191, 'Mocheta Dreptunghiulara 62', 0, 160.00, 100.00, 'Image171.png', 'Aceasta mocheta iti inspira modestie,putere si omenie.', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 192, 'Mocheta Dreptunghiulara 63', 0, 160.00, 100.00, 'Image172.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 06:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 193, 'Mocheta Dreptunghiulara 64', 0, 160.00, 100.00, 'Image173.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 194, 'Mocheta Dreptunghiulara 65', 0, 160.00, 100.00, 'Image174.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 195, 'Mocheta Dreptunghiulara 66', 0, 160.00, 100.00, 'Image175.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 196, 'Mocheta Dreptunghiulara 67', 0, 160.00, 100.00, 'Image176.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 197, 'Mocheta Dreptunghiulara 68', 0, 160.00, 100.00, 'Image177.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 198, 'Mocheta Dreptunghiulara 69', 0, 160.00, 100.00, 'Image178.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 199, 'Mocheta Dreptunghiulara 70', 0, 160.00, 100.00, 'Image179.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 200, 'Mocheta Dreptunghiulara 71', 0, 160.00, 100.00, 'Image180.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 201, 'Mocheta Dreptunghiulara 72', 0, 160.00, 100.00, 'Image181.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 202, 'Mocheta Dreptunghiulara 73', 0, 160.00, 100.00, 'Image182.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 203, 'Mocheta Dreptunghiulara 74', 0, 160.00, 100.00, 'Image183.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 204, 'Mocheta Dreptunghiulara 75', 0, 160.00, 100.00, 'Image184.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 205, 'Mocheta Dreptunghiulara 76', 0, 160.00, 100.00, 'Image185.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry'),
(1000, 206, 'Mocheta Dreptunghiulara 77', 0, 160.00, 100.00, 'Image186.png', 'Mocheta noua este cu putere ascunsa din cuvinte divine si in fața putere psihogeometrala', NULL, 0, '2026-02-18 04:58:34', 1, NULL, NULL, 0.00, NULL, 'PsyGeometry');

--
-- Indexuri pentru tabele eliminate
--

--
-- Indexuri pentru tabele `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pentru tabele eliminate
--

--
-- AUTO_INCREMENT pentru tabele `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=207;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
